---
- hosts: k8s-nodes
  remote_user: oneoneone
  become: yes
  become_method: sudo

  tasks:
  - name: add key for docker repo
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: add key for kubernetes repo
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present
  - name: add repo for docker
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      state: present
  - name: add repo for kubernetes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present

  - name: install dependencies for docker and kubernetes
    package: name={{item}} state=latest
    with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - bash-completion
  - name: install docker
    package: name={{item}} state=latest
    with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  - name: install kubernetes
    package: name={{item}} state=latest
    with_items:
    - kubelet
    - kubeadm
    - kubectl

  - name: copy docker config
    copy: src=/etc/ansible/docker/daemon.json dest=/etc/docker/daemon.json
            owner=root group=root mode=0644
    notify:
    - restart docker service

  handlers:
  - name: restart docker service
    service:
      name: docker
      state: restarted
